<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="entityRelation" nsURI="http://www.example.org/entityRelation"
    nsPrefix="erd">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Diagram">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueEntityNames validRelationships"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueEntityNames" value="entities->isUnique(e | e.name)"/>
      <details key="validRelationships" value="relationships->forAll(r | entities->includes(r.sourceEntity) and entities->includes(r.targetEntity))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" ordered="false"
        upperBound="-1" eType="#//Entity" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" ordered="false"
        upperBound="-1" eType="#//Relationship" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueAttributeNames primaryKeyIsAttribute"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueAttributeNames" value="attributes->isUnique(a | a.name)"/>
      <details key="primaryKeyIsAttribute" value="attributes->includes(primaryKey)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" ordered="false"
        upperBound="-1" eType="#//Attribute" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryKey" lowerBound="1"
        eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//AttributeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttributeType">
    <eLiterals name="string"/>
    <eLiterals name="boolean"/>
    <eLiterals name="float"/>
    <eLiterals name="integer"/>
    <eLiterals name="date"/>
    <eLiterals name="object"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" lowerBound="1"
        eType="#//CardinalityType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEntity" lowerBound="1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetEntity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CardinalityType">
    <eLiterals name="OneToOne"/>
    <eLiterals name="OneToMany"/>
    <eLiterals name="ManyToOne"/>
    <eLiterals name="ManyToMany"/>
  </eClassifiers>
</ecore:EPackage>
